 self.toolButton.setStyleSheet(u"\n"
"\n"
"\n"
".QToolButton {\n"
"	box-shadow:inset 0px 1px 0px 0px #f5f5f5;\n"
"	background-color:transparent;\n"
"	border:1px solid #fa0505;\n"
"	display:inline-block;\n"
"	cursor:pointer;\n"
"	color:#ff0303;\n"
"	font-family:Arial;\n"
"	font-size:17px;\n"
"	font-weight:bold;\n"
"	padding:16px 21px;\n"
"	text-decoration:none;\n"
"}\n"
".QToolButton:checked {\n"
"	\n"
"	\n"
"	box-shadow: 0px 0px 0px 0px #3dc21b;\n"
"	background:linear-gradient(to bottom, #44c767 5%, #6fdb34 100%);\n"
"	background-color:#44c767;\n"
"	display:inline-block;\n"
"	cursor:pointer;\n"
"	color:#ffffff;\n"
"	font-family:Arial;\n"
"	font-size:17px;\n"
"	font-weight:bold;\n"
"	\n"
"	text-decoration:none;\n"
"}\n"
".QToolButton:active {\n"
"	position:relative;\n"
"	top:1px;\n"
"}\n"
"")